### ISSUE TITLE
.APK DOWNLOAD

### ISSUE THREAD

**Issue by D19A66B55** [sultanahamer/PermissionsManager#33]
Could you please put the .apk download link directly to your software in Releases?
Waiting for F-droid is just ridiculous not to say that loss of interest in waiting for the download.
I actually don't understand the reasoning why some Github software creators don't add the download link in Releases.
Thank you for your time.

**Comment by sultanahamer** [comment]
@D19A66B55 instead of having download link for every release, We can do CI setup and get a build every push. That is the setup I have for my other app OpenContacts in gitlab.

Also

**Comment by D19A66B55** [comment]
Creating a dl link for .apk releases is the most convenient for the users, at least this user finds it very helpful.
I get the notification, go to releases & dl the apk. Done.
My suggestion-why not just release the apk for the major versions though, I sometimes like to dabble in the beta versions but, how is the CI easier for us & you rather than the simple dl link?

**Comment by sultanahamer** [comment]
check this project https://gitlab.com/sultanahamer/OpenContacts

You can find a download link in `Latest debug app` section

**Comment by D19A66B55** [comment]
> CI will auto generate new build for every code change we push. Its a simple download link for simple users and can give much more for advanced users

Thank you. CI sounds like the way to go.

**Comment by sultanahamer** [comment]
@D19A66B55 
Added the debug app link in the readme of this repository. CI has been integrated in Gitlab. So, on every push of code, we will have a new app here.

On the other hand, will deprecate this repository in favor of https://gitlab.com/sultanahamer/PermissionsManager

Try the download and we can close this issue once you are able to download.

**Comment by D19A66B55** [comment]
Downloaded app. All went well.
Thanks again.

**Comment by sultanahamer** [comment]
@D19A66B55 I am archiving this repository, we can follow the development on gitlab further
